services:
  - type: web
    name: budget-app
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn Sarc.wsgi:application --bind 0.0.0.0:$PORT